// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: events/user/v1/user_events.proto

package usereventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRegistered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"` // "user.registered"
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	OccurredAt    int64                  `protobuf:"varint,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // unix seconds (полезно для отладки/идемпотентности)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegistered) Reset() {
	*x = UserRegistered{}
	mi := &file_events_user_v1_user_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegistered) ProtoMessage() {}

func (x *UserRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_events_user_v1_user_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegistered.ProtoReflect.Descriptor instead.
func (*UserRegistered) Descriptor() ([]byte, []int) {
	return file_events_user_v1_user_events_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegistered) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *UserRegistered) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRegistered) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRegistered) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserRegistered) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

var File_events_user_v1_user_events_proto protoreflect.FileDescriptor

const file_events_user_v1_user_events_proto_rawDesc = "" +
	"\n" +
	" events/user/v1/user_events.proto\x12\x0eevents.user.v1\"\x92\x01\n" +
	"\x0eUserRegistered\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1f\n" +
	"\voccurred_at\x18\x05 \x01(\x03R\n" +
	"occurredAtBGZEgithub.com/hassiimykyta/life-rpg/services/events/user/v1;usereventsv1b\x06proto3"

var (
	file_events_user_v1_user_events_proto_rawDescOnce sync.Once
	file_events_user_v1_user_events_proto_rawDescData []byte
)

func file_events_user_v1_user_events_proto_rawDescGZIP() []byte {
	file_events_user_v1_user_events_proto_rawDescOnce.Do(func() {
		file_events_user_v1_user_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_user_v1_user_events_proto_rawDesc), len(file_events_user_v1_user_events_proto_rawDesc)))
	})
	return file_events_user_v1_user_events_proto_rawDescData
}

var file_events_user_v1_user_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_user_v1_user_events_proto_goTypes = []any{
	(*UserRegistered)(nil), // 0: events.user.v1.UserRegistered
}
var file_events_user_v1_user_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_user_v1_user_events_proto_init() }
func file_events_user_v1_user_events_proto_init() {
	if File_events_user_v1_user_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_user_v1_user_events_proto_rawDesc), len(file_events_user_v1_user_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_user_v1_user_events_proto_goTypes,
		DependencyIndexes: file_events_user_v1_user_events_proto_depIdxs,
		MessageInfos:      file_events_user_v1_user_events_proto_msgTypes,
	}.Build()
	File_events_user_v1_user_events_proto = out.File
	file_events_user_v1_user_events_proto_goTypes = nil
	file_events_user_v1_user_events_proto_depIdxs = nil
}
